import Script from "next/script"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}
        <Script src="https://code.jquery.com/jquery-3.7.1.min.js" />
      </body>
    </html>
  )
}
